### ISSUE TITLE
functions createTag fails when the full file path where the code is has a space character

### ISSUE THREAD

**Issue by JaviBonilla** [appwrite/sdk-for-cli#10]
If the full file path where the code is located has a space character, i.e. `/home/javi/functions/analyze Image/` the functions createTag command

```bash
appwrite functions createTag \
    --functionId=60dcbc0b83abc \
    --command='python main.py' \
    --code='./deploy'
```

fails with this error.

```bash
docker: invalid reference format.
See 'docker run --help'.
```

Otherwise, `/home/javi/functions/analyzeImage/`, it works fine.

- Appwrite CLI 0.10.0
- Docker version 20.10.6-ce, build 8728dd246c3a
- Linux linux-openSUSE 5.12.13-1-default

**Comment by christyjacob4** [comment]
@JaviBonilla  Thank you for raising this :smiley: 

https://github.com/appwrite/sdk-generator/pull/228 Should fix it :+1:

**Comment by JaviBonilla** [comment]
@christyjacob4 Great! Thanks.

There is another kind of issue, when the size of the `code.tar.gz` is greater than the given in `_APP_STORAGE_LIMIT`environment variable, the deployment fails and this warning (which doesn`t clearly point to the issue) is given.

```
Warning: Invalid argument supplied for foreach() in /usr/local/code/src/Parser.php on line 47
```

Could you try to replicate that?

**Comment by christyjacob4** [comment]
@JaviBonilla  Yes , I was able to replicate it and this PR https://github.com/appwrite/sdk-generator/pull/229  has a fix for that as well :smile:  
Thanks for helping with the debugging

**Comment by JaviBonilla** [comment]
Thanks @christyjacob4

**Comment by eldadfux** [comment]
This fix is now available in the latest CLI release.
