### ISSUE TITLE
🚀 Feature: Improve Homebrew integration

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-cli#101]
### 🔖 Feature description

1. You should be able to upgrade the Appwrite CLI. 
2. The homebrew method should probably install a binary rather than call `npm install`

### 🎤 Pitch

Upgrading the CLI currently doesn't work.

Also, since it installs via npm, if the npm on the OS is old, the CLI may not work.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by EVDOG4LIFE** [comment]
This looks to be resolved with https://github.com/Homebrew/homebrew-core/pull/162695

**Comment by EVDOG4LIFE** [comment]
Nevermind, `brew upgrade appwrite` doesn't function. `appwrite -v` returns `4.2.0` still.

**Comment by stnguyen90** [comment]
Should be resolved as long as you remove the old installation that uses our custom tap. You can also try to remove the custom tap by running:

```
brew untap appwrite/sdk-for-cli
```
