### ISSUE TITLE
📚 Documentation: Insufficient examples in documentation about some cli options

### ISSUE THREAD

**Issue by Weav3r** [appwrite/sdk-for-cli#102]
### 💭 Description

First of all, thanks for all your hard work.
The cli has been great, however, I've been facing a couple of issues figuring out how to use some of the command options more spcifically how to build queries using **--queries**. This is little documentation on how to build the queries. The only resource that gives a bit of a hint on how to do that is the [issue](https://github.com/appwrite/appwrite/issues/2875) on the main appwrite repository but after trying it it still doesn't work. Please any help concerning how to build the queries would be greatly appreciated. Thank you.
P.S. emulating the examples in the referenced issue, here's what I tried and other variations of it which did not work.
`appwrite users list --queries="phone.equal('+123456789')";`

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Weav3r, thanks for creating this issue! 🙏🏼 You can find an example of how to send multiple arguments [here](https://github.com/appwrite/sdk-for-cli?tab=readme-ov-file#usage) and [here](https://appwrite.io/docs/tooling/command-line/commands#create-document). In addition, the string you would pass for the query is documented [here](https://appwrite.io/docs/apis/rest#queries). As such, it should look like:

```bash
appwrite users list --queries 'equal("phone", "+123456789")'
```

**Comment by Weav3r** [comment]
@stnguyen90 Forgot I created this issue. You answered the same post about this on Discord a while ago. Thanks.
