### ISSUE TITLE
🐛 Bug Report: appwrite cli logout automatically

### ISSUE THREAD

**Issue by StarZeus** [appwrite/sdk-for-cli#110]
### 👟 Reproduction steps

1. Login to appwrite instance from appwrite-cli with `appwrite login` command and console user id and password
2. Retrieve project details with `appwrite projects get --projectId <id>
3. Able to retrieve project details
4. Retrieve project details with `appwrite projects get --projectId <id>
5. Getting error message saying "Error User (role: guests) missing scope (projects.read)"

Regardless of what command we execute 2nd time onwards the command fails as the user is not logged in anymore

### 👍 Expected behavior

appwrite cli should stay logged in until logout

### 👎 Actual Behavior

appwrite cli logout automatically after each command

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version 1.4.7 installed on kubernetes v1.20
appwrite-cli@4.1.0 installed on mac os Monterey

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by StarZeus** [comment]
@stnguyen90 raised https://github.com/StarZeus/sdk-generator/pull/1

**Comment by stnguyen90** [comment]
@StarZeus, thanks for creating this PR. Would you please create the PR to target our repo instead of your forked master branch?

**Comment by StarZeus** [comment]
@stnguyen90 - I have raised a new [PR](https://github.com/appwrite/sdk-generator/pull/802) targeting appwrite repo.
