### ISSUE TITLE
Can't deploy function where remote has variables

### ISSUE THREAD

**Issue by Ruboka** [appwrite/sdk-for-cli#112]
[Github Doc with the wrong line](https://github.com/appwrite/website/blob/ec0d6e605ee68dc8570605f004c59b92574a033f/src/routes/docs/tooling/command-line/deployment/%2Bpage.markdoc#L121C4-L121C13)

For Functions the option for the environment variables in this documentation has an error in its text. 
It should be  "vars" and not "variables".

```json
 "functions": [
    {
      "$id": "655dfe83ea1cd538c65c",
      "name": "createDocument",
      "runtime": "node-20.0",
      "execute": ["any"],
      "events": [],
      "schedule": "",
      "timeout": 15,
      "enabled": true,
      "logging": true,
      "entrypoint": "src/main.js",
      "commands": "npm install",
      "ignore": ["node_modules", ".npm"],
      "path": "functions/createDocument",
      "vars": { "apikey": "test" } // not variables
    }
  ]
```

If tried to deploy with variables the cli throws an error 
✗ Error remoteVariables is not defined

**Comment by stnguyen90** [comment]
Ahh I see the problem. There was a bug introduced in 4.2.0:

https://github.com/appwrite/sdk-for-cli/blob/ae7f9fecbbe5cc0cc702e878fd48cc8559fa18b2/lib/commands/deploy.js#L303-L316
