### ISSUE TITLE
🐛 Bug Report: accountCreateEmailSession is not a function

### ISSUE THREAD

**Issue by Marius-brt** [appwrite/sdk-for-cli#116]
### 👟 Reproduction steps

Try login to appwrite running on my local docker

### 👍 Expected behavior

Logged to my account

### 👎 Actual Behavior

`Error accountCreateEmailSession is not a function`

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite V1.5.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by idan054** [comment]
Any update? What should i do?

**Comment by stnguyen90** [comment]
@idan054, you can:
1. Wait for the next release
2. Use an older version
3. Modify the source code yourself locally

**Comment by stnguyen90** [comment]
FYI, we've relased 5.0.1: https://github.com/appwrite/sdk-for-cli/releases/tag/5.0.1
