### ISSUE TITLE
Shell appwrite init conf is reset after updating a property

### ISSUE THREAD

**Issue by Solido** [appwrite/sdk-for-cli#12]
Complete `appwrite init steps` 

then update any property 
`appwrite client setLocale --locale="en-US"`

End up with 
`❌ Oops We were unable to load your preferences. Ensure that you have run 'appwrite init' before using the CLI`

Setup under powershell

**Comment by christyjacob4** [comment]
@Solido , We released CLI 0.15 and this should no longer be an issue 🙂
