### ISSUE TITLE
🐛 Bug Report: Cannot deploy collections in appwrite.json with Int Attributes

### ISSUE THREAD

**Issue by maximilianmaihoefner** [appwrite/sdk-for-cli#124]
### 👟 Reproduction steps

1. Create a new Integer Attribute via the Web Interface, enter a name and leave all other fields empty and click create.
2. Connect the Appwrite CLI 2.0 using `appwrite login`
3. Create `appwrite.json` using `appwrite init --all`
4. Inspect the Integer Attribute in `appwrite.json`, it should show a min/max value of `-9223372036854776000`/`9223372036854776000`.
5. Try to deploy the `appwrite.json` using `appwrite deploy collection`
6. Choose the collection and confirm the overwrite.
7. An Error gets thrown.

### 👍 Expected behavior

Should be able to apply the created `appwrite.json`.

It would also be nice if the error message could specify the allowed min/max values, or a bit more description why the passed value is invalid.

### 👎 Actual Behavior

$ appwrite deploy collection
? Which collections would you like to deploy? MyCollection (62212c12df87ffcd4478)
ℹ Info Deploying collection MyCollection ( 62212c12df87ffcd4478 )
ℹ Info Collection MyCollection ( 62212c12df87ffcd4478 ) already exists.
? Are you sure you want to override this collection? This can lead to loss of data! Type "YES" to confirm. YES
ℹ Info Updating attributes ... 
✗ Error Invalid min: Value must be a valid integer

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

Using Appwrite 0.13.0 but that isn't available in the 'Appwrite version'-Dropdown yet.

The Server was upgraded from 0.12.1 using the instructions at: https://appwrite.io/docs/upgrade running the Install and Data Migration commands.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Reopening since it's still a problem. Related thread:

* https://discord.com/channels/564160730845151244/1220421739029332119
