### ISSUE TITLE
🚀 Enhancement: Sync cloud functions config with appwrite.json 

### ISSUE THREAD

**Issue by Weav3r** [appwrite/sdk-for-cli#126]
### 🔖 Enhancement description

There is currently no way to sync functions created/modified in the console with the `appwrite.json` config file. Changes made to a project, collections and buckets can be synced with the `init` command  to update the `appwrite.json`. 

### 🎤 Pitch

I propose a similar command (not necessarily `init`) be available to sync functions on the console with the `appwrite.json` using the cli.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by TheMaverickProgrammer** [comment]
I second this. Additionally, `appwrite init function ` prompts me to _create_ a new function whereas `appwrite init collection` and `appwrite init database` both sync to the `appwrite.json` file! This is not intuitive at all if this is the intended behavior for `function` option. Especially considering the `--help` and documentation each mention no difference between these!

**Comment by Weav3r** [comment]
Closing issue as it's fixed with the release of Appwrite 1.6.0 and cli 6.x.x which introduces the push and pull commands.
