### ISSUE TITLE
🐛 Bug Report: Can't initialize a python ML function

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-cli#129]
### 👟 Reproduction steps

1. `appwrite init function`
2. select "Python (ML) (python-ml-3.11)"

### 👍 Expected behavior

The function is created

### 👎 Actual Behavior

error:

```
$ appwrite init function
? What would you like to name your function? My Awesome Function
? What ID would you like to have for your function? unique()
? What runtime would you like to use? Python (ML) (python-ml-3.11)
✗ Error ENOENT: no such file or directory, copyfile '/Users/steven/Projects/appwrite-projects/local-delete/functions/My Awesome Function/python-ml-3.11' -> '/Users/steven/Projects/appwrite-projects/local-delete/functions/My Awesome Function'
```

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Tested using version 5.0.5 of the CLI

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
@stnguyen90 The reason we can't do this right now, is the old sdk-for-cli versions 5.0.x and below are still pointing to /function-starters instead of /templates repo.

This means the ML starters don't exist there yet. I see that on master for SDK generator this is already fixed, but cannot confirm because the latest RC releases' binaries aren't working for mac.

What I would do is confirm that this has been fixed in SDK versions 6.0.x and above, then cherry pick the fixes into 5.0.x and close this task.

**Comment by choir27** [comment]
On Appwrite CLI version 1.6, the user will be able to successfully initialize a python ML function starter. 

```
 appwrite init functions
? What would you like to name your function? My Awesome Function
? What ID would you like to have for your function? unique()
? What runtime would you like to use? Python (ML) (python-ml-3.11)       
? How would you like to start your function code? Start from scratch     
(starter)
✓ Success: 
ℹ Info: Next you can use 'appwrite run function' to develop a function locally. To deploy the function, use 'appwrite push function'
```
```
 appwrite init functions
? What would you like to name your function? My Awesome Function
? What ID would you like to have for your function? unique()
? What runtime would you like to use? Python (ML) (python-ml-3.11)       
? How would you like to start your function code? Pick a template        
? What template would you like to use? starter
✓ Success: 
ℹ Info: Next you can use 'appwrite run function' to develop a function locally. To deploy the function, use 'appwrite push function'
```
<img width="626" alt="Screenshot 2024-07-15 101749" src="https://github.com/user-attachments/assets/f9282e4e-67cc-49bf-9b54-48996e6a3ec8">

**Comment by gewenyu99** [comment]
Should we cherry pick the changes to 1.5?

**Comment by choir27** [comment]
> Should we cherry pick the changes to 1.5?

After confirming that these changes have already been incorporated into the current version of CLI and Appwrite, there is no need to cherry pick the changes to 1.5
