### ISSUE TITLE
bug: the term 'appwrite' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by yeikel16** [appwrite/sdk-for-cli#13]
After installing the install script from the CLI without problem, it does not recognize `appwrite` as a command within the console. I am using PowerShell to run the command.

```PowerShell
appwrite: The term 'appwrite' is not recognized as the name of a cmdlet, function, script file, or executable program. Check
if you typed the name correctly, or if you included a path, verify that the path is correct and try again.
Online: 1 Character: 1
+ appwrite version
+ ~~~~~~~~
     + CategoryInfo: ObjectNotFound: (appwrite: String) [], CommandNotFoundException
     + FullyQualifiedErrorId: CommandNotFoundException 
```

**Comment by eldadfux** [comment]
@christyjacob4 @TorstenDittmann any ideas?

**Comment by NeonSpork** [comment]
@yeikel16 Did this problem resolve when you restarted powershell?

**Comment by jonorozcoc** [comment]
It's not solved after restarting the console

**Comment by yeikel16** [comment]
n

> @yeikel16 Did this problem resolve when you restarted powershell?

Sorry for the late reply, restarting the console didn't fix the problem.
To solve this problem you have to install the CLI by `npm install -g appwrite-cli` and not by `iwr -useb https://appwrite.io/cli/install.ps1 | iex`, because the latter causes such an error.
I close this issue for now.

**Comment by Curiouspaul1** [comment]
perhaps take it out from the docs ? or fix the issue
