### ISSUE TITLE
Appwrite Database CreateCollection

### ISSUE THREAD

**Issue by shadowshot-x** [appwrite/sdk-for-cli#16]
I am trying to create a collection using Appwrite CLI. However, I cannot get the command to work. Each command throws a Server Error Message. I followed the examples and also tried to pass the parameters

`appwrite database createCollection --name="todo-crud" --read="["*"]" --write="["*"]" --rules="[ {"label":"Name","key":"name","type":"text","default":"Empty Name","required":true,"array":false},]"`

I get param read not optional if I run the below command
`appwrite database createCollection --name="todo-crud" --read="" --write="" --rules=""`

**Comment by lohanidamodar** [comment]
With new cli this might not be relevant.

**Comment by christyjacob4** [comment]
@shadowshot-x  We released CLI 0.15 and this should no longer be an issue 🙂
