### ISSUE TITLE
Init function does not work on Windows

### ISSUE THREAD

**Issue by rdmchr** [appwrite/sdk-for-cli#29]
It seems that some commands used by the CLI are Linux exclusive: https://github.com/appwrite/sdk-for-cli/blob/aed828f37740dad6e3453d12d2e102c50df3db67/lib/commands/init.js#L75

**Comment by christyjacob4** [comment]
@rdmchr  Thank you for  raising this . We will get this fixed 👍 
As a temporary workaround, please use WSL while we fix it.

**Comment by stnguyen90** [comment]
We'll track this in https://github.com/appwrite/sdk-for-cli/issues/30 as there are a few more comments in there.
