### ISSUE TITLE
Hard wrap STDOUT past 100-120 columns

### ISSUE THREAD

**Issue by kodumbeats** [appwrite/sdk-for-cli#3]
As an example, `appwrite help` produces a list of services. Zero of these lines are under 80 columns, `["storage", "users"]` are the only under 100 (the [current linux kernel standard](https://www.phoronix.com/scan.php?page=news_item&px=Linux-Kernel-Deprecates-80-Col)), and the longest line `teams` is 149 columns. 

Just a style preference, but it's a pain point to resize my terminal every time I use the CLI.

**Comment by christyjacob4** [comment]
@kodumbeats thank you for raising this. I was just working on this today. 

Do you have any suggestions to tackle this?

**Comment by kodumbeats** [comment]
My first thoughts after perusing these scripts:
- [the code](https://github.com/appwrite/sdk-for-cli/blob/master/app/Appwrite/Services/functions.php#L46) loops through `printf` with some padding in the front. Could first run the output string through [`wordwrap()`](https://www.php.net/manual/en/function.wordwrap.php), and then fiddle with the padding right before writing to STDOUT.
- Might be worth a refactor to check all output just for consistency. Maybe [`Manipulators.php`](https://github.com/appwrite/sdk-for-cli/blob/master/src/Manipulators.php) is the right place to check wrapping.

**Comment by christyjacob4** [comment]
I'll experiment with `wordwrap()` and let you know. 
I was thinking of moving this logic of calculating the padding etc to `Parser.php` since `Manipulators.php` is specific to the `jc21` table library that we are using.

**Comment by kodumbeats** [comment]
Aha, `Parser.php` looks like a better place. :) Most of the necessary abstraction logic is already in [`parseResponse`](https://github.com/appwrite/sdk-for-cli/blob/master/src/Parser.php#L53) it seems.

**Comment by christyjacob4** [comment]
![Screenshot 2021-02-23 at 10 09 52 PM](https://user-images.githubusercontent.com/20852629/108876088-db4b2500-7623-11eb-921d-940cf191eff9.png)
@kodumbeats

**Comment by christyjacob4** [comment]
https://github.com/appwrite/sdk-generator/pull/112
