### ISSUE TITLE
'appwrite init function' doesn't work on Windows

### ISSUE THREAD

**Issue by watzon** [appwrite/sdk-for-cli#30]
Seems like there might be something linux specific with `appwrite init function`.  When attempting on Windows I get 
```
Error ENOENT: no such file or directory, open 'C:\...\functions\My Awesome Function\README.md'
```

Node version: v17.7.1
Appwrite CLI version: 0.15.0

Tried with both CMD and Powershell

**Comment by christyjacob4** [comment]
You're right @watzon Thank you for raising this. We're using Unix specific `mkdir` in the code causing it to fail on Windows. 
As a temporary work around, please use WSL. 

We have this noted and we'll fix it soon 🙂

**Comment by anandsubbu007** [comment]
any update?

**Comment by Meldiron** [comment]
Addressed in PR: https://github.com/appwrite/sdk-generator/pull/406

**Comment by stnguyen90** [comment]
Duplicate of https://github.com/appwrite/sdk-for-cli/issues/29

**Comment by DanielAlbertSwan** [comment]
The Windows specific code is missing in current master is this intended?

**Comment by stnguyen90** [comment]
> The Windows specific code is missing in current master is this intended?

Thanks for bringing this up! 🙏  The code seems to have disappeared. 🧐 We'll look into it and fix it ASAP.

**Comment by stnguyen90** [comment]
@DanielAlbertSwan, we just pushed 0.18.4. How does it look now?

**Comment by DanielAlbertSwan** [comment]
Yes now it is working
