### ISSUE TITLE
appwrite deploy function catch SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by sendyputra** [appwrite/sdk-for-cli#33]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `appwrite-cli@0.16.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/appwrite-cli/lib/commands/functions.js b/node_modules/appwrite-cli/lib/commands/functions.js
index 1e90aac..90e22af 100644
--- a/node_modules/appwrite-cli/lib/commands/functions.js
+++ b/node_modules/appwrite-cli/lib/commands/functions.js
@@ -169,7 +169,7 @@ const functionsUpdate = async ({ functionId, name, execute, vars, events, schedu
     }
 
     if (typeof vars !== 'undefined') {
-        payload['vars'] = JSON.parse(vars);
+        payload['vars'] = vars
     }
 
     if (typeof events !== 'undefined') {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by PortStone** [comment]
Having the same issue as well. Is this going to get fixed?

**Comment by loicgeek** [comment]
@sendyputra  what about doing this instead? ```    if (typeof vars !== 'undefined') {
       try {
        payload['vars'] = JSON.parse(vars);
       } catch (error) {
        payload['vars'] =vars;
       }
    }```

**Comment by sendyputra** [comment]
@loicgeek Interesting catch json parse with trycatch 👍

**Comment by DmitriyIgnashchenko** [comment]
how can I fix this issue?

**Comment by Meldiron** [comment]
Addressed in a PR: https://github.com/appwrite/sdk-generator/pull/427

**Comment by stnguyen90** [comment]
Version 0.17.1 has been released to fix this.

**Comment by stnguyen90** [comment]
@sendyputra can this be closed now?
