### ISSUE TITLE
Unable to login to appwrite instance on azure from cli

### ISSUE THREAD

**Issue by Curiouspaul1** [appwrite/sdk-for-cli#35]
Hi i'm having some issues logging in to my appwrite instance on an Azure VM, via the cli, i set the appwrite client --endpoint to the hostname (http://tgappwrite.eastus.cloudapp.azure.com) of the VM (which is an alias for the public IP), the link opens up fine and i can open up the appwrite instance from the browser and login from there as well, but when i try logging in i keep getting this "NOt found" error, I've been stuck here for a while please help.

![image](https://user-images.githubusercontent.com/45743339/167609615-93c5a874-c71e-4196-9a62-fba380e5a57f.png)

**Comment by stnguyen90** [comment]
Can you try with /v1 at the end of the endpoint?

**Comment by stnguyen90** [comment]
Have you had a chance to check your endpoint? Btw you should use https rather than http.
