### ISSUE TITLE
[BUG] Login to a selfsigned host

### ISSUE THREAD

**Issue by dedonnodev** [appwrite/sdk-for-cli#37]
Hi there!
I discovered that with the 0.17.1 version i can't `appwrite login` to a self signed host (like localhost).

If i downgrade to the Appwrite Cli 0.15 it works without problems.
But with a "prefs.conf" already configured, the 0.17.1 version works.

PS: appwrite 0.14.2

**Comment by stnguyen90** [comment]
Your prefs.json needs to have a self signed flag set to true. You can also set it via the CLI.

**Comment by stnguyen90** [comment]
Have you checked if your prefs.json has the self signed option set?

**Comment by dedonnodev** [comment]
Hi there,
what i mean was that by CLI i couldn't login to a self signed host, but only if i set it manually in prefs.json.

Actually i didn't test with new versions. If it will happen, i will open a new issue.
Have a good day!
