### ISSUE TITLE
Handling arrays returned from API

### ISSUE THREAD

**Issue by kodumbeats** [appwrite/sdk-for-cli#4]
When an API response returns an array, the CLI doesn't properly handle arrays. Because of this, as an example, permissions cannot be viewed via the CLI.

From the endpoint `/v1/storage/files/{fileId}`, the `$permissions` field is empty:
```bash

aspire :: ~ » appwrite storage getFile --fileId="6032c58d7ccb6"
$id : 6032c58d7ccb6
$permissions :
name : fnlist.png
dateCreated : 1613940109
signature : cea8e7c354353f26d9fbd4755005b518
mimeType : image/png
sizeOriginal : 26184
```

From `/v1/storage/files` and `v1/functions`, `$permissions` returns only the array with length in parentheses:

![arrays](https://user-images.githubusercontent.com/9708641/108638202-084cdb80-745c-11eb-8a25-b77a8378f53c.png)

**Comment by eldadfux** [comment]
Has this been fixed on 0.6.0 @christyjacob4 @kodumbeats ?

**Comment by kodumbeats** [comment]
Looks like it's still an issue:
![arraysincli](https://user-images.githubusercontent.com/9708641/110794474-cd142000-8243-11eb-8fc8-f4e0683d1ea4.png)

**Comment by christyjacob4** [comment]
@eldadfux @kodumbeats Since the arrays can have an indefinite amount of nesting, I had decided to display only the first level of arrays in the form of a table. Once we decide on a proper logic to handle nested arrays and how to display them, I'll go ahead with the implementation
