### ISSUE TITLE
Can't login via cli to appwrite 0.15.x

### ISSUE THREAD

**Issue by squallsama** [appwrite/sdk-for-cli#40]
`appwrite login`
? Enter your email **************
? Enter your password **********
? Enter the endpoint of your Appwrite server  **************

And got:

`✗ Error Param "userId" is not optional.`

**Comment by adityaoberai** [comment]
@squallsama we're making some final updates, so the Appwrite CLI will have support for v0.15.x soon.

Keep an eye out on our [Discord server](https://appwrite.io/discord) for more info on this.

**Comment by ameerfayiz** [comment]
> @squallsama we're making some final updates, so the Appwrite CLI will have support for v0.15.x soon.
> 
> Keep an eye out on our [Discord server](https://appwrite.io/discord) for more info on this.

any updates??

**Comment by adityaoberai** [comment]
> > @squallsama we're making some final updates, so the Appwrite CLI will have support for v0.15.x soon.
> > 
> > Keep an eye out on our [Discord server](https://appwrite.io/discord) for more info on this.
> 
> any updates??

@Meldiron has been working on the CLI and we're currently doing more QA to ensure that you don't face any issues in the updated CLI

You can keep an eye out for these here: https://github.com/appwrite/sdk-generator/pull/484

**Comment by grisoftumut** [comment]
any progress? we stucked on cli on new release.

**Comment by ameerfayiz** [comment]
Any clue on when will the bug be fixed ?? Stuck on CLI 0.17.1 with appwrite 0.15.1

**Comment by adityaoberai** [comment]
We'll be sharing all updates regarding this issue on the PR here: [appwrite/sdk-generator#484](https://github.com/appwrite/sdk-generator/pull/484)

It is just undergoing final QA, and should be merged soon. Closing this issue for now as it is redundant.

**Comment by squallsama** [comment]
But it's still valid. Maybe it's better to close issue after releasing fix ?
