### ISSUE TITLE
Can't login via cli to appwrite 0.17.1

### ISSUE THREAD

**Issue by NasserGo** [appwrite/sdk-for-cli#41]
(base) ➜  ~ appwrite login
? Enter your email *************
? Enter your password *************
✗ Error Param "userId" is not optional.

**Comment by stnguyen90** [comment]
This looks to be the same as https://github.com/appwrite/sdk-for-cli/issues/40. A fix should be going out soon.

**Comment by NasserGo** [comment]
> 

 in my case , the appwrite ci dont ask the  endpoint of Appwrite server

**Comment by stnguyen90** [comment]
>  in my case , the appwrite ci dont ask the  endpoint of Appwrite server

This is probably because it's already set. You can see what it's set to by running

```
appwrite client --debug
```

**Comment by NasserGo** [comment]
> 

No solution found yet, currently cli can't login

**Comment by stnguyen90** [comment]
Related PR: https://github.com/appwrite/sdk-generator/pull/484

**Comment by stnguyen90** [comment]
Released! Please upgrade and try with 0.18.1!

**Comment by grisoftumut** [comment]
finally, thank for your effort
