### ISSUE TITLE
Bug: 0.18.2: Cannot find module './database'

### ISSUE THREAD

**Issue by TheMardy** [appwrite/sdk-for-cli#44]
The 0.18.2 release throws an error when trying to execute. On Windows as well as Linux.
```
Error: Cannot find module './database'
Require stack:
- /snapshot/sdk-for-cli/lib/commands/init.js
- /snapshot/sdk-for-cli/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/sdk-for-cli/lib/commands/init.js:9:37)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/sdk-for-cli/lib/commands/init.js',
    '/snapshot/sdk-for-cli/index.js'
  ],
  pkg: true
}
```
Downgrading to 0.18.1 works fine.

**Comment by JakeAi** [comment]
> The 0.18.2 release throws an error when trying to execute. On Windows as well as Linux.
> 
> ```
> Error: Cannot find module './database'
> Require stack:
> - /snapshot/sdk-for-cli/lib/commands/init.js
> - /snapshot/sdk-for-cli/index.js
> 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at Module.require (pkg/prelude/bootstrap.js:1719:31)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/snapshot/sdk-for-cli/lib/commands/init.js:9:37)
>     at Module._compile (pkg/prelude/bootstrap.js:1794:22)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/snapshot/sdk-for-cli/lib/commands/init.js',
>     '/snapshot/sdk-for-cli/index.js'
>   ],
>   pkg: true
> }
> ```
> 
> Downgrading to 0.18.1 works fine.

Can confirm, Just posted in discord 10 mins ago.
