### ISSUE TITLE
Deploy collection will set database name equal to database Id

### ISSUE THREAD

**Issue by dedonnodev** [appwrite/sdk-for-cli#47]
How to reproduce:
- From a new project create a database and a collection
- execute `appwrite init collection --all`
- delete database created from appwrite console
- execute `appwrite deploy collection --all`

Appwrite CLI deploy the right database and collection, but put in database's name the database's id

**Comment by dedonnodev** [comment]
I made a pull request i think with the fix
#48

**Comment by dedonnodev** [comment]
Wait a moment, i just understand what happen. If you run "appwrite init collection --all" it doesn't save database name, but only Id.
I got confused between collection name and database stuff.

So, my question is, why it doesn't save databseName? Or why it doesn't save database object in "appwrite.json" file as do with collection objects?

**Comment by stnguyen90** [comment]
@christyjacob4, would you be able to answer this?
