### ISSUE TITLE
🐛 Bug Report: Homebrew updates stuck with v0.15.0

### ISSUE THREAD

**Issue by soufi** [appwrite/sdk-for-cli#52]
### 👟 Reproduction steps

Install the CLI using homebrew : 
```
brew tap appwrite/sdk-for-cli https://github.com/appwrite/sdk-for-cli
brew update
brew install --HEAD appwrite
```
The version I get is v0.15.0

### 👍 Expected behavior

I should get the latest version v.0.18.4

### 👎 Actual Behavior

I am having v.0.15.0 even after running a `brew upgrade`

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by wess** [comment]
Thank you for submitting this issue. Can you please run `brew doctor` and let me know if you see any issues?

Thanks!

**Comment by soufi** [comment]
Hello @wess, No issues when running `brew doctor` the result is `Your system is ready to brew.`

**Comment by stnguyen90** [comment]
@wess, perhaps it would be good to set up a repo for homebrew like [sentry](https://github.com/getsentry/homebrew-tools).  To install the sentry cli, you would run:

```
brew install getsentry/tools/sentry-cli
```

**Comment by stnguyen90** [comment]
@wess another reason why this is broken is the formula is pointing to the wrong branch: 

https://github.com/appwrite/sdk-for-cli/blob/6d19ac0dd68de82ab78b3ec4f02ea2a5f90dabca/Formula/appwrite.rb#L7
