### ISSUE TITLE
🐛 Bug Report: Issue with installing AppWrite using the terminal command

### ISSUE THREAD

**Issue by stillie** [appwrite/sdk-for-cli#57]
### 👟 Reproduction steps

When I installed AppWrite CLI for the first time using `curl -sL https://appwrite.io/cli/install.sh | bash` then running `appwrite -v` I get an error

### 👍 Expected behavior

Installing AppWrite with Terminal should work fine

### 👎 Actual Behavior
After installing AppWrite using the terminal command and then running `appwrite -v` I get the following error:

```
/snapshot/sdk-for-cli/lib/questions.js:258
message: 'Are you sure you want to override this function's variables? This can lead to loss of secrets! Type "YES" to confirm.'
                                                              ^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:354:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Module._compile (pkg/prelude/bootstrap.js:1801:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
```

But when installing AppWrite with HomeBrew 
 ```
brew tap appwrite/sdk-for-cli https://github.com/appwrite/sdk-for-cli

brew update

brew install --HEAD appwrite
```

the installation works fine

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by sunnycat1991** [comment]
我也遇到了这个问题！

**Comment by sunnycat1991** [comment]
I had this problem too!

**Comment by sunnycat1991** [comment]
Operating system ====> windows 11

**Comment by stnguyen90** [comment]
@stillie, this seemed to work fine for me:

```
$ curl -sL https://appwrite.io/cli/install.sh | bash


     _                            _ _           ___   __   _____ 
    /_\  _ __  _ ____      ___ __(_) |_ ___    / __\ / /   \_   \
   //_\\| '_ \| '_ \ \ /\ / / '__| | __/ _ \  / /   / /     / /\/
  /  _  \ |_) | |_) \ V  V /| |  | | ||  __/ / /___/ /___/\/ /_  
  \_/ \_/ .__/| .__/ \_/\_/ |_|  |_|\__\___| \____/\____/\____/  
        |_|   |_|                                                


🔥 Welcome to the Appwrite CLI install shield 🛡
[1/4] Getting System Info ...

OS : darwin 
ARCH : arm64 
REQUIRES ROOT : true

[2/4] Downloading executable for darwin (arm64) ...
🚦 Downloading Appwrite CLI 1.1.1 ... 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 50.5M  100 50.5M    0     0  20.2M      0  0:00:02  0:00:02 --:--:-- 24.7M
✅ Done ... 

[3/4] Installing ...
🚧 Setting Permissions 
✅ Done ... 

📝 Copying temporary file to /usr/local/bin/appwrite ... 
Password:
✅ Done ... 

[4/4] Wrapping up installation ... 
🧹 Cleaning up mess ... 
✅ Done ... 

🤘 May the force be with you. 
🚀 To get started with Appwrite CLI, please visit https://appwrite.io/docs/command-line

$ /usr/local/bin/appwrite -v
1.1.1
```

What was the output of the install command when you ran it?

Also, are you on Appwrite 0.15.x? If so, you shouldn't be installing the latest CLI.

**Comment by stnguyen90** [comment]
> I had this problem too!

@sunnycat1991, what was the output of your install?

**Comment by stillie** [comment]
@stnguyen90 What OS did you run your command on? I was installing it on macOS Monterey 12.5.1

**Comment by stnguyen90** [comment]
@stillie, M1 MacOS 12.3.

**Comment by stillie** [comment]
v18.9.0

**Comment by stillie** [comment]
As I mentioned earlier, I couldn't install it with `curl -sL https://appwrite.io/cli/install.sh | bash` but I managed to get it installed with Home-brew I just wanted to highlight this issue incase there was a problem that no one was aware of

**Comment by stnguyen90** [comment]
@stillie oh wait...your problem is Appwrite version...You're running Appwrite Version 0.15.x. When you installed via `curl -sL https://appwrite.io/cli/install.sh | bash`, it installed the latest version of the CLI which doesn't work on Appwrite 0.15.x. You actually got lucky with the homebrew installation method because that's stuck on the CLI version for 0.15.x.
