### ISSUE TITLE
Move CLI entry point into its own file

### ISSUE THREAD

**Issue by cadenkriese** [appwrite/sdk-for-cli#6]
The CLI entry point is currently stored inside of the [install script](https://github.com/appwrite/sdk-for-cli/blob/master/install.sh#L127). I want to propose moving it to its own file as it will make alternate install methods (such as homebrew) easier to implement.

**Comment by christyjacob4** [comment]
@cadenkriese  We released CLI 0.15 and this should no longer be an issue 🙂
