### ISSUE TITLE
🚀 Feature: Clarify when no functions are deployed

### ISSUE THREAD

**Issue by InfiniteVerma** [appwrite/sdk-for-cli#63]
### 🔖 Feature description

If the user runs `appwrite deploy function` and presses `enter` without selecting any function, the CLI proceeds without informing user of anything. 

If the user (like me) doesn't read the instructions properly, they might press `enter` and think the first function has been deployed. 

https://user-images.githubusercontent.com/45547198/195146201-83f2f0f0-8f9f-48cf-a144-68c848be3440.mp4

### 🎤 Pitch

Prompt the user to select at least one function to deploy. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by MoskalykA** [comment]
I would like to do this if it is acceptable
