### ISSUE TITLE
🐛 Bug Report: Error Param "region" is not optional.

### ISSUE THREAD

**Issue by Faiyyaz** [appwrite/sdk-for-cli#66]
### 👟 Reproduction steps

run ```appwrite init project``` command

### 👍 Expected behavior

The project should have been created

### 👎 Actual Behavior

The project is not creating and giving the issue in the title

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Faiyyaz Is your Appwrite server version 1.1.2? If not, would you please try Appwrite 1.1.2?

**Comment by Faiyyaz** [comment]
Yes my appwrite version is 1.1.2

<img width="1440" alt="Screenshot 2022-12-12 at 10 26 01 AM" src="https://user-images.githubusercontent.com/18116236/206963803-7bdbc1b0-25d2-49a8-a62c-f99605ebedd8.png">

Also i am not able to login now it gives below error

<img width="1440" alt="Screenshot 2022-12-12 at 10 27 17 AM" src="https://user-images.githubusercontent.com/18116236/206963992-f539a817-7c08-43eb-96cc-6d4953ff1354.png">

**Comment by stnguyen90** [comment]
@Faiyyaz, are you still having this problem, or can this be closed now?

**Comment by Faiyyazk** [comment]
@stnguyen90 I didn't checked it recently. Maybe give me sometime i will confirm if i can reproduce this

**Comment by Faiyyaz** [comment]
@stnguyen90 I didn't checked it recently. Maybe give me sometime i will confirm if i can reproduce this

**Comment by stnguyen90** [comment]
@Faiyyaz, have you had a chance to test? Maybe I can close this, and you can open a new issue if the problems persist.

**Comment by Faiyyaz** [comment]
@stnguyen90 Hey sorry for so late reply. I tried installing the new version but now it shows bad gateway error

<img width="1440" alt="Screenshot 2023-05-08 at 10 05 32 PM" src="https://user-images.githubusercontent.com/18116236/236882269-a4304b20-40e8-41fc-b231-9e3d01d1e93e.png">

**Comment by Faiyyaz** [comment]
@stnguyen90 I am able to login successfully now. Thanks for the help!
