### ISSUE TITLE
🐛 Bug Report: Deploy not including all files in src/ python:3.9

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [appwrite/sdk-for-cli#68]
### 👟 Reproduction steps

I like to split my python project into multiple files as modules but the deploy command is not including those files with the `index.py`.

File structure:
![image](https://user-images.githubusercontent.com/45077772/208308525-b4e534c9-297a-4cfc-8106-b0a15eceacec.png)

List dir of `index.py` directory from function execution:
![image](https://user-images.githubusercontent.com/45077772/208308553-fffb6a11-c54d-4ddb-8388-d579847e36ef.png)

As you can see no other file from `src/` was shipped with index.py

### 👍 Expected behavior

It should have the extra files in the same dir as the `index.py` file

### 👎 Actual Behavior

No extra files shipped to function using deploy command.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@DEADSEC-SECURITY how did you deploy your function?

Also, FYI, what you listed is the current working directory of the function runtime, rather than the folder with your source code. Your source code should be in the `userlib` folder. What do you see in there?

**Comment by DEADSEC-SECURITY** [comment]
Let me check whats inside userlib then.
I deployed using the node.js deploy command

**Comment by DEADSEC-SECURITY** [comment]
`{"src":["synologyFTP.py","__pycache__","__init__.py","schemas.py","index.py"],"userlib":["README.md","requirements.txt","runtime-env","src"]}`

Well the files are being sent but for some reason I cant import them? 
Well os.getcwd gets the current file dir and since its not printing the correct file I suppose python wont find the relative files too?
@stnguyen90 any ideas?

**Comment by DEADSEC-SECURITY** [comment]
From the docs: Return a unicode string representing the current working directory.
Which means src folder is not current dir meaning python wont be able to realtive import unless files are in the os.getcwd printed dir!
I think this is a bug but let me know what you think @stnguyen90

**Comment by stnguyen90** [comment]
@DEADSEC-SECURITY for python imports, I suggest using relative imports. So your index.py would import schemas.py like:

```python
from .schemas import thing
```

or something like that.

**Comment by DEADSEC-SECURITY** [comment]
Ill test it with that syntax. I was using with out the dot before the file name which vould cause problems like in this instance. Maybe forcing same path import can fix it.

**Comment by DEADSEC-SECURITY** [comment]
Hmm seems to work with that syntax. Which makes sense.

As a note for future readers:
Force relative import with a .<package_name> instead of <package_name> only
