### ISSUE TITLE
🐛 Bug Report: CLI only matches on collection id rather than database id and collection id 

### ISSUE THREAD

**Issue by saidhasyim** [appwrite/sdk-for-cli#74]
### 👟 Reproduction steps

1. Create 2 databases.
2. In each database, create a collection. Both with the same collection ID
3. Run appwrite init collection
4. Select all collections

### 👍 Expected behavior

CLI shall write all databases into the appwrite.json

### 👎 Actual Behavior

CLI only writes 1 set of database into appwrite.json

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Local docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @saidhasyim - Thanks for creating this issue, our team will be reviewing this ASAP
