### ISSUE TITLE
Failed to execute process '/usr/local/bin/appwrite'.

### ISSUE THREAD

**Issue by DanTheMinotaur** [appwrite/sdk-for-cli#8]
When executing appwrite in a non-bash shell (I'm using [fish](https://fishshell.com/)). It will respond with unknown error. 

```bash 
> appwrite
Failed to execute process '/usr/local/bin/appwrite'. Reason:
exec: unknown error (errno was 8)
The file '/usr/local/bin/appwrite' is marked as an executable but could not be run by the operating system.
```

This is due to their being a newline before the shebang. It can be fixed by removing the newline. 

**/usr/local/bin/appwrite**
```

#!/bin/bash
...
```

Probably an non-issue but thought I'd leave it here if anyone else runs into this.

**Comment by christyjacob4** [comment]
@DanTheMinotaur  Please let me know if this is still an issue with the latest `CLI 0.15.0`

**Comment by stnguyen90** [comment]
@DanTheMinotaur can this be closed now?

**Comment by DanTheMinotaur** [comment]
@stnguyen90 all good now 👍
