### ISSUE TITLE
🚀 Feature: Support Initializing a Project in an Existing Organization

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/sdk-for-cli#83]
### 🔖 Feature description

Right now, initializing a project creates a new organization:

https://github.com/appwrite/sdk-for-cli/blob/b4619977eb95ca6650aa5291eb6a26d6bfa46eda/lib/commands/init.js#L32-L37

It would be helpful to allow creating as part of an existing organization.

### 🎤 Pitch

Creating in an existing organization makes organizing the project easier/cleaner.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Jaishree2310** [comment]
@stnguyen90 Please assign this issue token to me?

**Comment by Haimantika** [comment]
> @stnguyen90 Please assign this issue token to me?

Hi, we have already assigned you two issues. That’s the maximum number of issues we can assign at a time to one person

**Comment by probablyArth** [comment]
I'd like to get assigned!

**Comment by probablyArth** [comment]
Here's what I have in mind :-
- add another question `do you want to create project in an existing organisation?`
- if yes then another question - `enter teamId` OR `select from the list of teams`

**Comment by gewenyu99** [comment]
> @gewenyu99 what do you think of this?
> 
> Perhaps the first "How would you like to start?" should have two options:
> 
> 1. Create a new organization
> 2. Use an existing organization
> 
> "Use an existing organization" would show a list of organizations (teams) the user can select from. Make sure to show the organization name and ID [like we do for project](https://github.com/appwrite/sdk-for-cli/blob/b0b59eea974f5b77e88aaba72fd141587d6ce6f8/lib/questions.js#L170).
> 
> Then, ask, "Would you like to create a new project or link to an existing?".
> 
> If they select "Link this directory to an existing Appwrite project" make sure to filter the results to the projects under the chosen organization. This would help when you have the same project name in multiple organizations.

I like this approach. Make sure to include a non-interactive option!

**Comment by probablyArth** [comment]
got it, ill start working on it 👌

**Comment by Haimantika** [comment]
> got it, ill start working on it 👌

Hi, are you working on it? If not, we will be reassigning the issue to the next person due to inactivity from your end.
