### ISSUE TITLE
Failed to connect to localhost: Connection refused with status code 0

### ISSUE THREAD

**Issue by andydean565** [appwrite/sdk-for-cli#9]
I have set up appwrite write using docker-compose on my localhost, but the CLI won't connect to the server

- windows

**Comment by christyjacob4** [comment]
Hey @andydean565 
Can you make the following request in postman and share the output ? 

Method : GET
Url : <Your endpoint>/v1/locale/continents

Headers:
`x-appwrite-project` : `Your project ID`

**Comment by andydean565** [comment]
```
{
    "sum": 7,
    "continents": [
        {
            "name": "Africa",
            "code": "AF"
        },
        {
            "name": "Antarctica",
            "code": "AN"
        },
        {
            "name": "Asia",
            "code": "AS"
        },
        {
            "name": "Europe",
            "code": "EU"
        },
        {
            "name": "North America",
            "code": "NA"
        },
        {
            "name": "Oceania",
            "code": "OC"
        },
        {
            "name": "South America",
            "code": "SA"
        }
    ]
}
```

**Comment by christyjacob4** [comment]
If this works, then you should be able to use the same endpoint( including /v1) and project ID in `appwrite init` and it should work

**Comment by andydean565** [comment]
have managed to get it working and am unsure if the issue was down to when I setup the appwrite host from `localhost` to `0.0.0.0` 

or 

i was originally working through powerShell with wsl but have since changed to setting everything up in wsl ubuntu (including the CLI)
